# Generated by Django 5.2.3 on 2025-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstateListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listed_on_page", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_posted", models.DateField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("offer_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("square_meters", models.IntegerField(blank=True, null=True)),
                (
                    "price_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("availability", models.URLField(blank=True, null=True)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_locality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_insert_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
