# Generated by Django 5.2.3 on 2025-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wgwatch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealEstateLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_locality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
